// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyResourceTrackerProtocol.proto

package com.ava.bigdata.common.rpc.hadoop.protobuf.proto;

public final class MyResourceTrackerProtocol {
  private MyResourceTrackerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code MyResourceTrackerService}
   *
   * <pre>
   * 用于描述要生成的API接口，service定义一个抽象内部类
   * </pre>
   */
  public static abstract class MyResourceTrackerService
      implements com.google.protobuf.Service {
    protected MyResourceTrackerService() {}

    public interface Interface {
      /**
       * <code>rpc registerNodeManager(.MyRegisterNodeManagerRequestProto) returns (.MyRegisterNodeManagerResponseProto);</code>
       *
       * <pre>
       * rpc定义一个抽象方法
       * </pre>
       */
      public abstract void registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request,
          com.google.protobuf.RpcCallback<com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MyResourceTrackerService() {
        @java.lang.Override
        public  void registerNodeManager(
            com.google.protobuf.RpcController controller,
            com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request,
            com.google.protobuf.RpcCallback<com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto> done) {
          impl.registerNodeManager(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.registerNodeManager(controller, (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc registerNodeManager(.MyRegisterNodeManagerRequestProto) returns (.MyRegisterNodeManagerResponseProto);</code>
     *
     * <pre>
     * rpc定义一个抽象方法
     * </pre>
     */
    public abstract void registerNodeManager(
        com.google.protobuf.RpcController controller,
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request,
        com.google.protobuf.RpcCallback<com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.registerNodeManager(controller, (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto)request,
            com.google.protobuf.RpcUtil.<com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerProtocol.MyResourceTrackerService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request,
          com.google.protobuf.RpcCallback<com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.class,
            com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:MyResourceTrackerService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037MyResourceTrackerProtocol.proto\032\036MyRes" +
      "ourceTrackerMessage.proto2z\n\030MyResourceT" +
      "rackerService\022^\n\023registerNodeManager\022\".M" +
      "yRegisterNodeManagerRequestProto\032#.MyReg" +
      "isterNodeManagerResponseProtoBS\n0com.ava" +
      ".bigdata.common.rpc.hadoop.protobuf.prot" +
      "oB\031MyResourceTrackerProtocol\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
