// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyResourceTrackerMessage.proto

package com.ava.bigdata.common.rpc.hadoop.protobuf.proto;

public final class MyResourceTrackerMessage {
  private MyResourceTrackerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyRegisterNodeManagerRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string hostname = 1;
    /**
     * <code>required string hostname = 1;</code>
     */
    boolean hasHostname();
    /**
     * <code>required string hostname = 1;</code>
     */
    java.lang.String getHostname();
    /**
     * <code>required string hostname = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    // required int32 cpu = 2;
    /**
     * <code>required int32 cpu = 2;</code>
     */
    boolean hasCpu();
    /**
     * <code>required int32 cpu = 2;</code>
     */
    int getCpu();

    // required int32 memory = 3;
    /**
     * <code>required int32 memory = 3;</code>
     */
    boolean hasMemory();
    /**
     * <code>required int32 memory = 3;</code>
     */
    int getMemory();
  }
  /**
   * Protobuf type {@code MyRegisterNodeManagerRequestProto}
   */
  public static final class MyRegisterNodeManagerRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements MyRegisterNodeManagerRequestProtoOrBuilder {
    // Use MyRegisterNodeManagerRequestProto.newBuilder() to construct.
    private MyRegisterNodeManagerRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyRegisterNodeManagerRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyRegisterNodeManagerRequestProto defaultInstance;
    public static MyRegisterNodeManagerRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public MyRegisterNodeManagerRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyRegisterNodeManagerRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hostname_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cpu_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              memory_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.class, com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MyRegisterNodeManagerRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<MyRegisterNodeManagerRequestProto>() {
      public MyRegisterNodeManagerRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyRegisterNodeManagerRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyRegisterNodeManagerRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string hostname = 1;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object hostname_;
    /**
     * <code>required string hostname = 1;</code>
     */
    public boolean hasHostname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string hostname = 1;</code>
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hostname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 cpu = 2;
    public static final int CPU_FIELD_NUMBER = 2;
    private int cpu_;
    /**
     * <code>required int32 cpu = 2;</code>
     */
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cpu = 2;</code>
     */
    public int getCpu() {
      return cpu_;
    }

    // required int32 memory = 3;
    public static final int MEMORY_FIELD_NUMBER = 3;
    private int memory_;
    /**
     * <code>required int32 memory = 3;</code>
     */
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 memory = 3;</code>
     */
    public int getMemory() {
      return memory_;
    }

    private void initFields() {
      hostname_ = "";
      cpu_ = 0;
      memory_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHostname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCpu()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, memory_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, memory_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto)) {
        return super.equals(obj);
      }
      com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto other = (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto) obj;

      boolean result = true;
      result = result && (hasHostname() == other.hasHostname());
      if (hasHostname()) {
        result = result && getHostname()
            .equals(other.getHostname());
      }
      result = result && (hasCpu() == other.hasCpu());
      if (hasCpu()) {
        result = result && (getCpu()
            == other.getCpu());
      }
      result = result && (hasMemory() == other.hasMemory());
      if (hasMemory()) {
        result = result && (getMemory()
            == other.getMemory());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHostname()) {
        hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getHostname().hashCode();
      }
      if (hasCpu()) {
        hash = (37 * hash) + CPU_FIELD_NUMBER;
        hash = (53 * hash) + getCpu();
      }
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyRegisterNodeManagerRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.class, com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.Builder.class);
      }

      // Construct using com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hostname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cpu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        memory_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerRequestProto_descriptor;
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto getDefaultInstanceForType() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.getDefaultInstance();
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto build() {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto buildPartial() {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto result = new com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostname_ = hostname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cpu_ = cpu_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.memory_ = memory_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto) {
          return mergeFrom((com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto other) {
        if (other == com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto.getDefaultInstance()) return this;
        if (other.hasHostname()) {
          bitField0_ |= 0x00000001;
          hostname_ = other.hostname_;
          onChanged();
        }
        if (other.hasCpu()) {
          setCpu(other.getCpu());
        }
        if (other.hasMemory()) {
          setMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHostname()) {
          
          return false;
        }
        if (!hasCpu()) {
          
          return false;
        }
        if (!hasMemory()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string hostname = 1;
      private java.lang.Object hostname_ = "";
      /**
       * <code>required string hostname = 1;</code>
       */
      public boolean hasHostname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hostname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder clearHostname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }

      // required int32 cpu = 2;
      private int cpu_ ;
      /**
       * <code>required int32 cpu = 2;</code>
       */
      public boolean hasCpu() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cpu = 2;</code>
       */
      public int getCpu() {
        return cpu_;
      }
      /**
       * <code>required int32 cpu = 2;</code>
       */
      public Builder setCpu(int value) {
        bitField0_ |= 0x00000002;
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cpu = 2;</code>
       */
      public Builder clearCpu() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpu_ = 0;
        onChanged();
        return this;
      }

      // required int32 memory = 3;
      private int memory_ ;
      /**
       * <code>required int32 memory = 3;</code>
       */
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 memory = 3;</code>
       */
      public int getMemory() {
        return memory_;
      }
      /**
       * <code>required int32 memory = 3;</code>
       */
      public Builder setMemory(int value) {
        bitField0_ |= 0x00000004;
        memory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 memory = 3;</code>
       */
      public Builder clearMemory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memory_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyRegisterNodeManagerRequestProto)
    }

    static {
      defaultInstance = new MyRegisterNodeManagerRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyRegisterNodeManagerRequestProto)
  }

  public interface MyRegisterNodeManagerResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string flag = 1;
    /**
     * <code>required string flag = 1;</code>
     */
    boolean hasFlag();
    /**
     * <code>required string flag = 1;</code>
     */
    java.lang.String getFlag();
    /**
     * <code>required string flag = 1;</code>
     */
    com.google.protobuf.ByteString
        getFlagBytes();
  }
  /**
   * Protobuf type {@code MyRegisterNodeManagerResponseProto}
   */
  public static final class MyRegisterNodeManagerResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements MyRegisterNodeManagerResponseProtoOrBuilder {
    // Use MyRegisterNodeManagerResponseProto.newBuilder() to construct.
    private MyRegisterNodeManagerResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyRegisterNodeManagerResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyRegisterNodeManagerResponseProto defaultInstance;
    public static MyRegisterNodeManagerResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public MyRegisterNodeManagerResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyRegisterNodeManagerResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              flag_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.class, com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MyRegisterNodeManagerResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<MyRegisterNodeManagerResponseProto>() {
      public MyRegisterNodeManagerResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyRegisterNodeManagerResponseProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyRegisterNodeManagerResponseProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private java.lang.Object flag_;
    /**
     * <code>required string flag = 1;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string flag = 1;</code>
     */
    public java.lang.String getFlag() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          flag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string flag = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFlagBytes() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      flag_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFlagBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFlagBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto)) {
        return super.equals(obj);
      }
      com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto other = (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto) obj;

      boolean result = true;
      result = result && (hasFlag() == other.hasFlag());
      if (hasFlag()) {
        result = result && getFlag()
            .equals(other.getFlag());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFlag()) {
        hash = (37 * hash) + FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getFlag().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyRegisterNodeManagerResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.class, com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.Builder.class);
      }

      // Construct using com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        flag_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.internal_static_MyRegisterNodeManagerResponseProto_descriptor;
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto getDefaultInstanceForType() {
        return com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance();
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto build() {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto buildPartial() {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto result = new com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto) {
          return mergeFrom((com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto other) {
        if (other == com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          bitField0_ |= 0x00000001;
          flag_ = other.flag_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFlag()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ava.bigdata.common.rpc.hadoop.protobuf.proto.MyResourceTrackerMessage.MyRegisterNodeManagerResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string flag = 1;
      private java.lang.Object flag_ = "";
      /**
       * <code>required string flag = 1;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string flag = 1;</code>
       */
      public java.lang.String getFlag() {
        java.lang.Object ref = flag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          flag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string flag = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFlagBytes() {
        java.lang.Object ref = flag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string flag = 1;</code>
       */
      public Builder setFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string flag = 1;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = getDefaultInstance().getFlag();
        onChanged();
        return this;
      }
      /**
       * <code>required string flag = 1;</code>
       */
      public Builder setFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyRegisterNodeManagerResponseProto)
    }

    static {
      defaultInstance = new MyRegisterNodeManagerResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyRegisterNodeManagerResponseProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MyRegisterNodeManagerRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyRegisterNodeManagerRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MyRegisterNodeManagerResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyRegisterNodeManagerResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036MyResourceTrackerMessage.proto\"R\n!MyRe" +
      "gisterNodeManagerRequestProto\022\020\n\010hostnam" +
      "e\030\001 \002(\t\022\013\n\003cpu\030\002 \002(\005\022\016\n\006memory\030\003 \002(\005\"2\n\"" +
      "MyRegisterNodeManagerResponseProto\022\014\n\004fl" +
      "ag\030\001 \002(\tBK\n)com.ava.bigdata.common.rpc.p" +
      "rotobuf.protoB\030MyResourceTrackerMessage\210" +
      "\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MyRegisterNodeManagerRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MyRegisterNodeManagerRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MyRegisterNodeManagerRequestProto_descriptor,
              new java.lang.String[] { "Hostname", "Cpu", "Memory", });
          internal_static_MyRegisterNodeManagerResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MyRegisterNodeManagerResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MyRegisterNodeManagerResponseProto_descriptor,
              new java.lang.String[] { "Flag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
